// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260426065116_updateChanges")]
    partial class updateChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Pname")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Price", "Stock");

                    b.ToTable("product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Computers",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Laptop",
                            Price = 50000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 2,
                            Category = "Accessories",
                            ImageUrl = "https://m.media-amazon.com/images/I/71udkMozQ3L._AC_SL1489_.jpg",
                            IsActive = true,
                            Pname = "Laptop Charger",
                            Price = 1500m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 3,
                            Category = "Phones",
                            ImageUrl = "https://th.bing.com/th/id/R.fc73ae7340a79785ed2ac6655051d0d6?rik=SEMYCU828IxtCw",
                            IsActive = true,
                            Pname = "Mobile",
                            Price = 25000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 4,
                            Category = "Accessories",
                            ImageUrl = "https://th.bing.com/th/id/OIP.L_XVZQ8Vz9zmYHG-27an_QHaGT?w=208&h=180&c=7&r=0&o=7&pid=1.7&rm=3",
                            IsActive = true,
                            Pname = "Mobile Charger",
                            Price = 500m,
                            Stock = 13
                        },
                        new
                        {
                            Id = 5,
                            Category = "Peripherals",
                            ImageUrl = "https://images.unsplash.com/photo-1587829741301-dc798b83add3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
                            IsActive = true,
                            Pname = "Wireless Mouse",
                            Price = 800m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 6,
                            Category = "Peripherals",
                            ImageUrl = "https://images.unsplash.com/photo-1593642634367-d91a135587b5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
                            IsActive = true,
                            Pname = "Mechanical Keyboard",
                            Price = 3000m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 7,
                            Category = "Peripherals",
                            ImageUrl = "https://m.media-amazon.com/images/I/81zLDfXdsfL.jpg",
                            IsActive = true,
                            Pname = "Gaming Headset",
                            Price = 2500m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 8,
                            Category = "Peripherals",
                            ImageUrl = "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04",
                            IsActive = true,
                            Pname = "Webcam",
                            Price = 1200m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 9,
                            Category = "Peripherals",
                            ImageUrl = "https://m.media-amazon.com/images/I/715OTcL3kaL._AC_SL1500_.jpg",
                            IsActive = true,
                            Pname = "USB Hub",
                            Price = 700m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 10,
                            Category = "Peripherals",
                            ImageUrl = "https://m.media-amazon.com/images/I/61wDfddKt5L._AC_.jpg",
                            IsActive = true,
                            Pname = "External Hard Drive",
                            Price = 4500m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 11,
                            Category = "Peripherals",
                            ImageUrl = "https://s13emagst.akamaized.net/products/50830/50829483/images/res_a126340b9468e6ebe28dfaef136309be.jpg",
                            IsActive = true,
                            Pname = "SSD 1TB",
                            Price = 8000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 12,
                            Category = "Peripherals",
                            ImageUrl = "https://s13emagst.akamaized.net/products/50830/50829483/images/res_a126340b9468e6ebe28dfaef136309be.jpg",
                            IsActive = true,
                            Pname = "Router",
                            Price = 3500m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 13,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Power Bank",
                            Price = 1200m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 14,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Smartwatch",
                            Price = 7000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 15,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Tablet",
                            Price = 15000m,
                            Stock = 9
                        },
                        new
                        {
                            Id = 16,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Laptop Stand",
                            Price = 900m,
                            Stock = 14
                        },
                        new
                        {
                            Id = 17,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "HDMI Cable",
                            Price = 400m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 18,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Ethernet Cable",
                            Price = 350m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 19,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Bluetooth Speaker",
                            Price = 1800m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 20,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Microphone",
                            Price = 2500m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 21,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Desk Lamp",
                            Price = 1200m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 22,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Office Chair",
                            Price = 5500m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 23,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Monitor 24 inch",
                            Price = 12000m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 24,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Monitor 27 inch",
                            Price = 18000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 25,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Laptop Sleeve",
                            Price = 700m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 26,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "USB Flash Drive",
                            Price = 500m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 27,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Graphics Card",
                            Price = 40000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 28,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Motherboard",
                            Price = 15000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 29,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Processor",
                            Price = 22000m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 30,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "RAM 16GB",
                            Price = 7000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 31,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "RAM 32GB",
                            Price = 12000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 32,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Cooling Fan",
                            Price = 1500m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 33,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "CPU Cooler",
                            Price = 3000m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 34,
                            Category = "Peripherals",
                            ImageUrl = "https://laptopmedia.com/wp-content/uploads/2024/09/Swift-Go-14-AI-02-e1725465393450.jpg",
                            IsActive = true,
                            Pname = "Graphics Card Cooler",
                            Price = 3500m,
                            Stock = 6
                        });
                });

            modelBuilder.Entity("Project.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Line2")
                        .HasColumnType("longtext");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Project.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Project.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Project.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("OrdersId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdersId");

                    b.HasIndex("ProductId", "OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Project.Models.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.HasIndex("CustomerName", "OrderDate");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Project.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Uname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Project.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Project.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WishlistId", "ProductId")
                        .IsUnique();

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("Project.Models.Address", b =>
                {
                    b.HasOne("Project.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Models.Cart", b =>
                {
                    b.HasOne("Project.Models.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("Project.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Models.CartItem", b =>
                {
                    b.HasOne("Project.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Project.Models.OrderItem", b =>
                {
                    b.HasOne("Project.Models.Orders", "Orders")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrdersId");

                    b.HasOne("Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Project.Models.Orders", b =>
                {
                    b.HasOne("Project.Models.Address", "OrderAddress")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Project.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Models.Wishlist", b =>
                {
                    b.HasOne("Project.Models.User", "User")
                        .WithOne("Wishlist")
                        .HasForeignKey("Project.Models.Wishlist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Models.WishlistItem", b =>
                {
                    b.HasOne("Product", "Product")
                        .WithMany("WishlistItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Wishlist", "Wishlist")
                        .WithMany("Items")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("Project.Models.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Project.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Project.Models.Orders", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Project.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Project.Models.Wishlist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
